### ISSUE TITLE
Vue components loaded within the normal content section are not replaced

### ISSUE THREAD

**Issue by madmpj** [centagon/build-core#20]
When trying to render vue components, such as bauhaus's custom <input-asset> or <page-container>
These components will not be rendered because bauhaus's content is rendered within the "Content" section and not in the "vue-content" section.

I suggest moving the #vue-wrapper to wrap the main content section so that any content can be vue-able

**Comment by jspekken** [comment]
@madmpj something like: https://github.com/centagon/build-core/pull/21 ? ;)
